version: "3.8"
services:

  db:
    image: "postgres:16.3"
    ports:
      - "5432:5432"
    volumes:
      - ~/.pgdata/base:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=python_template